/* Generated By:JavaCC: Do not edit this line. UserQueryConstants.java */
public interface UserQueryConstants {

  int EOF = 0;
  int GET = 1;
  int AND = 2;
  int OR = 3;
  int EQUALS = 4;
  int NOTEQUALS = 5;
  int NUM = 6;
  int SPACE = 7;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"GET\"",
    "\"&&\"",
    "\"||\"",
    "\"=\"",
    "\"!=\"",
    "<NUM>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
