/* Generated By:JavaCC: Do not edit this line. UserQueryConstants.java */
package com.amazon.zama_edoc.client;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UserQueryConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int JOIN = 1;
  /** RegularExpression Id. */
  int OPERATOR = 2;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int NAME = 4;
  /** RegularExpression Id. */
  int VALUE = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<JOIN>",
    "<OPERATOR>",
    "\" \"",
    "<NAME>",
    "<VALUE>",
    "\"\\n\"",
    "\"\\r\"",
  };

}
